#include <iostream>
#include <string>
#include <stdio.h>

void main() {

string nama = "Fadlillah Bashir Al Hakim";
string tanggallahir = "18 Juli 2003";
string tempatlahir = "Malang";
int umur = 19;
string jurusan = "Teknik Elektro";
string prodi = "D3 Teknik Telekomunikasi";
string kelas = "1C";

cout << "Halo, perkenalkan saya" << endl <<
"Nama : " + nama << endl << "Lahir di : " + tempatlahir + "," + tanggallahir << endl <<
"Umur : " + umur << endl << "Jurusan : " + jurusan << endl << "Prodi : " + prodi << endl << "kelas : " + kelas;

}