#include <iostream.h>
#include <stdio.h>
#include <string>
#include <conio.h>

using namespace std;

double a,b,c;

double main(){
	//header
	cout << " !_!_! Biggest Number Program !_!_!\n\n";

	//input
	cout << "Lebokno Nilai A Coy : "; cin >> a;
	cout << "Lebokno Nilai B Coy : "; cin >> b;
	cout << "Lebokno Nilai C Coy : "; cin >> c;

	cout << "\n\nNilai terbesar yo iku = " << max(a, b, c);
   return 0;

	getch();

}
