#include <iostream.h>
#include <conio.h>

//variabel perulangan
int a, b, i, j, k, p;

main(){

	cout << "PERULANGAN 2" << endl;
   cout << "Masukkan input anda : ";
	cin >> p;

   for(p=1,q=0,j=0,k=1; j<i; j++){
    	if (j % 2 == 0){
       	cout << p << " ";
         p = p + (8 * o);
         k++;
      }
      else if(j % 2 == 1){
      	a = a + 4;
         cout << a << " ";
      }
   }
   getch();
}